export const TIMEZONE_OPTIONS = [
  { value: "America/New_York", label: "Eastern Time (ET) - New York" },
  { value: "America/Chicago", label: "Central Time (CT) - Chicago" },
  { value: "America/Denver", label: "Mountain Time (MT) - Denver" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT) - Los Angeles" },
  { value: "America/Anchorage", label: "Alaska Time (AKT) - Anchorage" },
  { value: "Pacific/Honolulu", label: "Hawaii Time (HT) - Honolulu" },
  { value: "America/Phoenix", label: "Arizona (MST) - Phoenix" },
  { value: "America/Toronto", label: "Eastern Time (ET) - Toronto" },
  { value: "America/Vancouver", label: "Pacific Time (PT) - Vancouver" },
  { value: "America/Mexico_City", label: "Central Time (CST) - Mexico City" },
  { value: "America/Bogota", label: "Colombia Time (COT) - Bogota" },
  { value: "America/Lima", label: "Peru Time (PET) - Lima" },
  { value: "America/Santiago", label: "Chile Time (CLT) - Santiago" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina Time (ART) - Buenos Aires" },
  { value: "America/Sao_Paulo", label: "Brasilia Time (BRT) - São Paulo" },
  { value: "Europe/London", label: "GMT / BST - London" },
  { value: "Europe/Paris", label: "Central European (CET) - Paris" },
  { value: "Europe/Berlin", label: "Central European (CET) - Berlin" },
  { value: "Europe/Madrid", label: "Central European (CET) - Madrid" },
  { value: "Europe/Rome", label: "Central European (CET) - Rome" },
  { value: "Europe/Amsterdam", label: "Central European (CET) - Amsterdam" },
  { value: "Europe/Zurich", label: "Central European (CET) - Zurich" },
  { value: "Europe/Stockholm", label: "Central European (CET) - Stockholm" },
  { value: "Europe/Warsaw", label: "Central European (CET) - Warsaw" },
  { value: "Europe/Athens", label: "Eastern European (EET) - Athens" },
  { value: "Europe/Bucharest", label: "Eastern European (EET) - Bucharest" },
  { value: "Europe/Helsinki", label: "Eastern European (EET) - Helsinki" },
  { value: "Europe/Istanbul", label: "Turkey Time (TRT) - Istanbul" },
  { value: "Europe/Moscow", label: "Moscow Time (MSK) - Moscow" },
  { value: "Asia/Dubai", label: "Gulf Standard (GST) - Dubai" },
  { value: "Asia/Kolkata", label: "India Standard (IST) - Mumbai" },
  { value: "Asia/Bangkok", label: "Indochina Time (ICT) - Bangkok" },
  { value: "Asia/Singapore", label: "Singapore Time (SGT) - Singapore" },
  { value: "Asia/Hong_Kong", label: "Hong Kong Time (HKT) - Hong Kong" },
  { value: "Asia/Shanghai", label: "China Standard (CST) - Shanghai" },
  { value: "Asia/Tokyo", label: "Japan Standard (JST) - Tokyo" },
  { value: "Asia/Seoul", label: "Korea Standard (KST) - Seoul" },
  { value: "Australia/Sydney", label: "Australian Eastern (AEST) - Sydney" },
  { value: "Australia/Melbourne", label: "Australian Eastern (AEST) - Melbourne" },
  { value: "Australia/Perth", label: "Australian Western (AWST) - Perth" },
  { value: "Pacific/Auckland", label: "New Zealand (NZST) - Auckland" },
];

export function getTimezoneLabel(value: string): string {
  const tz = TIMEZONE_OPTIONS.find((t) => t.value === value);
  return tz ? tz.label : value;
}
