name: Deploy to ECR and EC2
on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_URL: https://leaves-tracking.copilotinnovations.com
      NEXT_PUBLIC_ENABLE_TEST_MODE: true
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to ECR and EC2
      uses: CoPilot-Innovations/ecr-ec2-deploy-action@v1.0.4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        ecr-repository: demo
        image-tag: copilot-lms-latest
        ec2-host: ${{ secrets.EC2_HOST }}
        ec2-user: ${{ secrets.EC2_USER }}
        ec2-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
        env-content: ${{ secrets.ENV_CONTENT }}
        container-name: copilot-lms
        host-port: '3001'
        container-port: '3001'
