export const TIMEZONE_OPTIONS = [
  { value: "America/New_York", label: "GMT-5 - New York" },
  { value: "America/Chicago", label: "GMT-6 - Chicago" },
  { value: "America/Denver", label: "GMT-7 - Denver" },
  { value: "America/Los_Angeles", label: "GMT-8 - Los Angeles" },
  { value: "America/Anchorage", label: "GMT-9 - Anchorage" },
  { value: "Pacific/Honolulu", label: "GMT-10 - Honolulu" },
  { value: "America/Phoenix", label: "GMT-7 - Phoenix" },
  { value: "America/Toronto", label: "GMT-5 - Toronto" },
  { value: "America/Vancouver", label: "GMT-8 - Vancouver" },
  { value: "America/Mexico_City", label: "GMT-6 - Mexico City" },
  { value: "America/Bogota", label: "GMT-5 - Bogota" },
  { value: "America/Lima", label: "GMT-5 - Lima" },
  { value: "America/Santiago", label: "GMT-3 - Santiago" },
  { value: "America/Argentina/Buenos_Aires", label: "GMT-3 - Buenos Aires" },
  { value: "America/Sao_Paulo", label: "GMT-3 - São Paulo" },
  { value: "Europe/London", label: "GMT+0 - London" },
  { value: "Europe/Paris", label: "GMT+1 - Paris" },
  { value: "Europe/Berlin", label: "GMT+1 - Berlin" },
  { value: "Europe/Madrid", label: "GMT+1 - Madrid" },
  { value: "Europe/Rome", label: "GMT+1 - Rome" },
  { value: "Europe/Amsterdam", label: "GMT+1 - Amsterdam" },
  { value: "Europe/Zurich", label: "GMT+1 - Zurich" },
  { value: "Europe/Stockholm", label: "GMT+1 - Stockholm" },
  { value: "Europe/Warsaw", label: "GMT+1 - Warsaw" },
  { value: "Europe/Athens", label: "GMT+2 - Athens" },
  { value: "Europe/Bucharest", label: "GMT+2 - Bucharest" },
  { value: "Europe/Helsinki", label: "GMT+2 - Helsinki" },
  { value: "Europe/Istanbul", label: "GMT+3 - Istanbul" },
  { value: "Europe/Moscow", label: "GMT+3 - Moscow" },
  { value: "Asia/Dubai", label: "GMT+4 - Dubai" },
  { value: "Asia/Kolkata", label: "GMT+5:30 - Mumbai" },
  { value: "Asia/Bangkok", label: "GMT+7 - Bangkok" },
  { value: "Asia/Singapore", label: "GMT+8 - Singapore" },
  { value: "Asia/Hong_Kong", label: "GMT+8 - Hong Kong" },
  { value: "Asia/Shanghai", label: "GMT+8 - Shanghai" },
  { value: "Asia/Tokyo", label: "GMT+9 - Tokyo" },
  { value: "Asia/Seoul", label: "GMT+9 - Seoul" },
  { value: "Australia/Sydney", label: "GMT+11 - Sydney" },
  { value: "Australia/Melbourne", label: "GMT+11 - Melbourne" },
  { value: "Australia/Perth", label: "GMT+8 - Perth" },
  { value: "Pacific/Auckland", label: "GMT+13 - Auckland" },
];

export function getTimezoneLabel(value: string): string {
  const tz = TIMEZONE_OPTIONS.find((t) => t.value === value);
  return tz ? tz.label : value;
}
